import raw from '@/data/boqItems.json';
import type { BOQColumnField, BOQEditableField, BOQFields, BOQItem, BOQOverride, BOQTable } from '@/types/boq';
import { BOQ_EDITABLE_FIELDS } from './boqValidation';

// Generated by scripts/import-boq.cjs; values are positional to keep the bundle small.
interface RawItem { id: string; table: number; sourceRow: number; sourceRows?: number[]; section?: string; roomLookup?: string; values: string[] }
const catalog = raw as unknown as { source: string; importedAt: string; tables: BOQTable[]; items: RawItem[] };

export const BOQ_SOURCE = { file: catalog.source, importedAt: catalog.importedAt };
export const NO_ROOM = 'Tanpa Ruangan';
export const CUSTOM_CATEGORY = 'Item Tambahan';
export { BOQ_EDITABLE_FIELDS };
export const BOQ_FIELD_LABELS: Record<BOQEditableField, string> = {
  ciName: 'CI Name', ciDescription: 'CI Description', capacity: 'Capacity', serialNumber: 'Serial Number',
  productionYear: 'Production Year', manufacturer: 'Manufacturer / Principle', assetId: 'Asset ID', tag: 'TAG', model: 'Model/Version',
};
const EDITABLE = new Set<BOQColumnField>(BOQ_EDITABLE_FIELDS);

export const boqTables: BOQTable[] = catalog.tables;
const CUSTOM_TABLE: BOQTable = {
  id: 'custom', sheet: CUSTOM_CATEGORY, sheetKey: 'custom', headerRow: 0, title: CUSTOM_CATEGORY,
  columns: [{ label: 'Class Id', field: 'classId' }, ...BOQ_EDITABLE_FIELDS.map(field => ({ label: BOQ_FIELD_LABELS[field], field })), { label: 'Floor', field: 'floor' }, { label: 'Room', field: 'room' }],
};
const tableById = new Map([...boqTables, CUSTOM_TABLE].map(table => [table.id, table]));
export const tableOf = (item: BOQItem) => tableById.get(item.tableId) || CUSTOM_TABLE;
export const tableOrder = (tableId: string) => { const index = boqTables.findIndex(table => table.id === tableId); return index < 0 ? boqTables.length : index; };

const emptyRoom = (value: string) => !value.trim() || /^(n\/?a|-+)$/i.test(value.trim());
// Room spelling varies in the workbook ("Crac Room 1", "1f crac room 1", "1F-CRAC ROOM 1"). Group ignoring case,
// spaces, hyphens, a leading "1F" floor prefix and a few recurring typos.
const ROOM_TYPOS: [RegExp, string][] = [[/CHILER/g, 'CHILLER'], [/TRAFOO/g, 'TRAFO'], [/INTERCONECTING/g, 'INTERCONNECTING'], [/KORIDOOR/g, 'KORIDOR']];
export const roomKeyOf = (room: string) => {
  if (emptyRoom(room)) return '';
  const key = ROOM_TYPOS.reduce((value, [typo, fix]) => value.replace(typo, fix), room.toUpperCase().replace(/[^A-Z0-9]+/g, ''));
  return key.replace(/^1F(?=[A-Z])/, '');
};
// Label for each room key: its most common spelling, preferring one that is not all lowercase.
export function roomLabelsOf(items: BOQItem[]): Map<string, string> {
  const spellings = new Map<string, Map<string, number>>();
  for (const item of items) {
    const key = roomKeyOf(item.room);
    if (!key) continue;
    const spelling = item.room.replace(/\s+/g, ' ').trim();
    const counts = spellings.get(key) || new Map<string, number>();
    counts.set(spelling, (counts.get(spelling) || 0) + 1);
    spellings.set(key, counts);
  }
  const score = ([spelling, count]: [string, number]) => count * 2 + (spelling === spelling.toLowerCase() ? 0 : 1) + (/^1f/i.test(spelling) ? 0 : 1);
  return new Map([...spellings].map(([key, counts]) => [key, tidyRoomName([...counts].sort((a, b) => score(b) - score(a))[0][0])]));
}
// "1f data hall 1.1 ," → "1F Data Hall 1.1": only rooms written entirely in lowercase are re-cased.
const tidyRoomName = (name: string) => {
  const trimmed = name.replace(/[\s,;.-]+$/, '');
  if (trimmed !== trimmed.toLowerCase()) return trimmed;
  return trimmed.replace(/\b(\d+f|[a-z])/g, (match: string) => match.toUpperCase());
};

export const boqItems: BOQItem[] = catalog.items.map(item => {
  const table = catalog.tables[item.table];
  const get = (field: BOQColumnField) => { const index = table.columns.findIndex(column => column.field === field); return index < 0 ? '' : item.values[index] || ''; };
  const roomCell = get('room');
  const fields = Object.fromEntries(BOQ_EDITABLE_FIELDS.map(field => [field, get(field)])) as BOQFields;
  return {
    ...fields,
    // Same fallback as the importer: some rows name the asset only in Class Id or CI Description.
    ciName: fields.ciName || get('classId') || fields.ciDescription,
    id: item.id, tableId: table.id, sheet: table.sheet, sourceSheet: table.sheetKey,
    sourceRow: item.sourceRow, sourceRows: item.sourceRows, section: item.section, values: item.values,
    room: emptyRoom(roomCell) ? item.roomLookup || '' : roomCell.trim(),
    roomFromLookup: emptyRoom(roomCell) && !!item.roomLookup,
    floor: get('floor'), classId: get('classId'),
  };
});

const workbookRoomLabels = roomLabelsOf(boqItems);
// Display name of a room; rooms only used by items added in the app keep their own spelling.
export const roomLabel = (room: string) => workbookRoomLabels.get(roomKeyOf(room)) || room.replace(/\s+/g, ' ').trim();

// A cell as currently known: the drafter's saved edit when the column maps to an editable field, else the workbook value.
export function cellValue(item: BOQItem, columnIndex: number, override?: BOQOverride) {
  const column = tableOf(item).columns[columnIndex];
  if (item.custom) {
    if (!column.field || column.field === 'no') return '';
    return (EDITABLE.has(column.field) ? override?.[column.field as BOQEditableField] : undefined) ?? item[column.field] ?? '';
  }
  if (column.field && EDITABLE.has(column.field) && override && override[column.field as BOQEditableField] !== undefined) {
    return override[column.field as BOQEditableField] || '';
  }
  return item.values[columnIndex] || '';
}

// Editable fields that exist as a column in the item's table (custom items can set all of them).
export function editableFieldsOf(item: BOQItem): BOQEditableField[] {
  if (item.custom) return BOQ_EDITABLE_FIELDS;
  const fields = new Set(tableOf(item).columns.map(column => column.field));
  return BOQ_EDITABLE_FIELDS.filter(field => field === 'ciName' || fields.has(field));
}

export const fieldsOf = (value: Partial<BOQFields>): BOQFields =>
  Object.fromEntries(BOQ_EDITABLE_FIELDS.map(field => [field, value[field] || ''])) as BOQFields;
